### ISSUE TITLE
Renew staging certificates

### ISSUE THREAD

**Issue by j0ni** [appcanary/agent#150]
> Hello,
> 
> Your certificate (or certificates) for the names listed below will expire in 19 days (on 09 Mar 17 19:05 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.
> 
> isitvuln.staging.appcanary.com
> rubysec.staging.appcanary.com
> www.isitvuln.staging.appcanary.com
> www.rubysec.staging.appcanary.com
> 
> For any questions or support, please visit https://community.letsencrypt.org/. Unfortunately, we can't provide support by email.
> 
> If you are receiving this email in error, unsubscribe at http://mandrillapp.com/track/unsub.php?u=30850198&id=8f00f39d03f7420fb9a330ffc1ec2858.Hzd6jPCviIzQoMwEkt6IG0Bo4HU%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Dhello%2540appcanary.com (HTTP link, we know. We're working on it!)
> 
> Regards,
> The Let's Encrypt Team
>

**Comment by mveytsman** [comment]
it's annoying that they email you but these are auto renewed by certbot afail
