### ISSUE TITLE
every damned linux startup script

### ISSUE THREAD

**Issue by phillmv** [appcanary/agent#61]
Debian:
- [ ] Debian Stretch
- [x] Debian Jessie
- [x] Debian Wheezy
- [ ] Debian Squeeze

Ubuntu:
- [x] Ubuntu Vivid
- [ ] Ubuntu Utopic
- [x] Ubuntu Trusty
- [x] Ubuntu Precise

RHEL:
- [x] RHEL7
- [x] RHEL6
- [ ] RHEL 5

CentOS:
- [x] CentOS 7
- [x] CentOS 6
- [ ] CentOS 5

Amazon Linux:
- [x] Amazon
- any others?

**Comment by MacLeodMike** [comment]
Any interest in SuSE? I hate it personally, but it's popular in Europe.

**Comment by MacLeodMike** [comment]
Also, are we really targeting debian stretch? Do people run the testing distro in production?

**Comment by phillmv** [comment]
Frankly only one that's come up by name is CentOS/Amazon and rhel, so in a case by case basis

**Comment by phillmv** [comment]
Calling this closed.
