### ISSUE TITLE
puppet install script

### ISSUE THREAD

**Issue by phillmv** [appcanary/agent#72]

**Comment by MacLeodMike** [comment]
https://github.com/MacLeodMike/puppet-appcanary

Should be what we need. Do you want to fork it, or just reference my repo directly?

**Comment by phillmv** [comment]
Transfer ownership to appcanary and we'll take it from there :).

On Sat, Jul 25, 2015 at 12:01 PM, MacLeodMike <notifications@github.com>
wrote:

> https://github.com/MacLeodMike/puppet-appcanary
>
> Should be what we need. Do you want to fork it, or just reference my repo
> directly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appcanary/agent/issues/72#issuecomment-124872816>.
>



-- 
Phillip Mendonça-Vieira
http://state.io
@phillmv <http://twitter.com/phillmv>
